poll/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from poll import views

app_name = 'poll'

urlpatterns = [
    # Login Pages
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('register/', views.register_page, name='register'),

    # Election Pages
    path('', views.hello, name='hello'),
    path('vote/', views.vote, name='vote'),
    path('notifications/', views.notifications, name='notifications'),
    path('choice/', views.candidates, name='choice', kwargs={'template_name': 'poll/choice.html'}),
    path('access-is-forbidden/', views.notice_access_is_forbidden, name='notice-access-is-forbidden'),
    path('results/', views.candidates, name='results', kwargs={'template_name': 'poll/results.html'}),
    path('candidates/', views.candidates, name='candidates', kwargs={'template_name': 'poll/candidates.html'}),
    path('detail/<int:candidate_id>/', views.detail, name='detail', kwargs={'template_name': 'poll/detail.html'}),

    # Participate Pages
    path('participate-sent/', views.notice_participate_sent, name='participate-sent'),
    path('participate/', views.create_participate_form, name='create-participate-form'),
    path('update-sent/', views.notice_participate_update_sent, name='participate-update-sent'),
    path('participate/<str:author>/', views.update_participate_form, name='update-participate-form'),
    path('change-status/', views.notice_participate_change_status, name='participate-warning-change-status'),
    path('candidate-already-exists', views.notice_participate_candidate_already_exists,
         name='participate-warning-candidate-already-exists'),

    # Moderator's Pages
    path('moderator-hello/', views.moderator_page, name='moderator-hello'),
    path('moderate/', views.moderator_moderate, name='moderator-moderate'),
    path('instruction/', views.moderator_instruction, name='moderator-instruction'),
    path('refuse/<int:candidate_id>/', views.moderator_refuse, name='moderator-refuse'),
    path('edit-instruction/', views.moderator_edit_instruction, name='moderator-edit-instruction'),
    path('candidate-refused/', views.notice_moderator_candidate_refused, name='notice-moderator-candidate-refused'),
    path('instruction-saved/', views.notice_moderator_instruction_saved, name='notice-moderator-instruction-saved'),
    path('candidate-accepted/', views.notice_moderator_candidate_accepted, name='notice-moderator-candidate-accepted'),
    path('moderator-candidates/', views.candidates, name='moderator-candidates',
         kwargs={'template_name': 'poll/moderator-candidates.html'}),
    path('moderator-detail/<int:candidate_id>', views.detail, name='moderator-detail',
         kwargs={'template_name': 'poll/moderator-detail.html'}),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poll.urls')),
]

poll/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser


def user_directory_path(instance, filename):
    return '{0}/{1}'.format(instance.author, filename)


class Candidate(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    fraction = models.CharField(max_length=20)
    biography = models.TextField()
    targets = models.CharField(max_length=1000)
    telephone = models.CharField(max_length=20)
    votes = models.IntegerField(default=0)
    refusal_reason = models.TextField(default='')
    moderated = models.BooleanField(default=False)
    avatar = models.ImageField(default='default-avatar.jpeg', upload_to=user_directory_path, null=True, blank=True)


class AdminData(models.Model):
    instruction = models.TextField(default='There is no instruction')

    # This function lets saving only one object of the class
    def save(self, *args, **kwargs):
        if not self.pk and AdminData.objects.exists():
            raise ValidationError('Can be only one AdminData instance')
        return super().save(*args, **kwargs)


class User(AbstractUser):
    checked_by_moderator = models.BooleanField(default=False)

    ELECTOR = 1
    CANDIDATE = 2
    MODERATOR = 3

    ROLE_CHOICES = (
        (ELECTOR, 'Elector'),
        (CANDIDATE, 'Candidate'),
        (MODERATOR, 'Moderator'),
    )

    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True)

poll/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Candidate, AdminData

User = get_user_model()


class CreateCandidateForm(ModelForm):
    class Meta:
        model = Candidate

        fields = [
            'name',
            'fraction',
            'telephone',
            'targets',
            'email',
            'biography',
            'avatar',
        ]

        widgets = {
            'biography': forms.Textarea(attrs={'rows': 3}),
        }


class ModerateCandidateForm(ModelForm):
    class Meta:
        model = Candidate

        fields = [
            'refusal_reason',
        ]

        widgets = {
            'refusal_reason': forms.Textarea(attrs={'rows': 3}),
        }


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User

        fields = [
            'username',
            'email',
            'password1',
            'password2',
        ]


class EditModeratorInstruction(ModelForm):
    class Meta:
        model = AdminData

        fields = [
            'instruction',
        ]

        widgets = {
            'instruction': forms.Textarea(attrs={'rows': 3}),
        }

poll/views.py
from django.http import Http404
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, authenticate, logout, get_user_model

from .models import Candidate, AdminData
from .decorators import unauthenticated_user, allowed_users
from .forms import CreateCandidateForm, ModerateCandidateForm, CreateUserForm, EditModeratorInstruction

User = get_user_model()


@unauthenticated_user
def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('poll:hello')
        else:
            messages.info(request, 'Username OR password is incorrect')

    return render(request, 'poll/login.html')


@unauthenticated_user
def register_page(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)

        if form.is_valid():
            user = form.save()

            user.role = User.ELECTOR
            user.save()

            username = form.cleaned_data.get('username')
            messages.success(request, 'Account was successfully create for ' + username)

    context = {'form': form}

    return render(request, 'poll/register.html', context)


@login_required(login_url='poll:login')
def logout_page(request):
    logout(request)
    return redirect('poll:login')


@login_required(login_url='poll:login')
@allowed_users(['Elector', 'Candidate'], ['all'])
def hello(request):
    context = standard_context(request)
    return render(request, 'poll/hello.html', context)


# Moderator has access to views 'candidate' and 'detail' because they are used in the logic of moderator's pages
@login_required(login_url='poll:login')
@allowed_users(['Elector', 'Candidate', 'Moderator'], ['all'])
def candidates(request, **kwargs):
    context = standard_context(request)

    candidates_list = Candidate.objects.order_by('name')
    context['candidates_list'] = candidates_list
    template = kwargs['template_name']

    return render(request, template, context)


@login_required(login_url='poll:login')
@allowed_users(['Elector', 'Candidate', 'Moderator'], ['all'])
def detail(request, candidate_id, **kwargs):
    context = standard_context(request)

    candidate = get_object_or_404(Candidate, pk=candidate_id)
    context['candidate'] = candidate
    template = kwargs['template_name']

    return render(request, template, context)


@login_required(login_url='poll:login')
@allowed_users(['Candidate'], ['Application Draft', 'Application Final'])
def notifications(request):
    context = standard_context(request)

    candidate = get_object_or_404(Candidate, author=request.user.username)
    context['moderated'] = candidate.moderated
    context['refusal_reason'] = candidate.refusal_reason

    return render(request, 'poll/notifications.html', context)


@login_required(login_url='poll:login')
@allowed_users(['Elector', 'Candidate'], ['all'], False)
def vote(request):
    try:
        selected_candidate = request.POST['choice']
    except(KeyError, Candidate.DoesNotExist):
        return Http404
    else:
        new_group = Group.objects.get(name='Voted')
        request.user.groups.add(new_group)

        candidate = get_object_or_404(Candidate, pk=selected_candidate)
        candidate.votes += 1
        candidate.save()

        return redirect('poll:results')


@login_required(login_url='poll:login')
@allowed_users(['Elector', 'Candidate'], ['Application Process'])
def create_participate_form(request):
    form = CreateCandidateForm()

    new_group = Group.objects.get(name='Application Process')
    request.user.groups.add(new_group)
    request.user.role = User.CANDIDATE
    request.user.save()

    context = standard_context(request)
    context['form'] = form

    if request.method == 'POST':
        form = CreateCandidateForm(request.POST, request.FILES)

        if form.is_valid():
            result_form = form.save(commit=False)
            result_form.author = request.user
            result_form.save()

            check_candidate(request, form)

            return change_group_by_button(request, form)

    return render(request, 'poll/participate.html', context)


@login_required(login_url='poll:login')
@allowed_users(['Candidate'], ['Application Draft'])
def update_participate_form(request, author):
    context = standard_context(request)

    # It checks if another user tries to change data of a foreign user
    if author != request.user.username:
        return redirect('poll:notice-access-is-forbidden')

    candidate = get_object_or_404(Candidate, author=author)
    form = CreateCandidateForm(instance=candidate)

    user = request.user
    if user.checked_by_moderator:
        context['refusal_reason'] = candidate.refusal_reason
        context['checked_by_moderator'] = True

    context['form'] = form

    if request.method == 'POST':
        form = CreateCandidateForm(request.POST, instance=candidate)

        if form.is_valid():
            form.save()
            check_candidate(request, form)

        return change_group_by_button(request, form)

    return render(request, 'poll/participate.html', context)


@login_required(login_url='poll:login')
@allowed_users(['Moderator'])
def moderator_page(request):
    context = standard_context(request)
    return render(request, 'poll/moderator-hello.html', context)


@login_required(login_url='poll:login')
@allowed_users(['Moderator'])
def moderator_moderate(request):
    if request.method == 'POST':
        selected_choice = request.POST['choice']
        selected_candidate = request.POST['candidate-id']

        candidate = get_object_or_404(Candidate, pk=selected_candidate)

        moderated_user = get_object_or_404(User, username=candidate.author)
        moderated_user.checked_by_moderator = True
        moderated_user.save()

        if selected_choice == 'ACCEPT':
            candidate.moderated = True
            candidate.save()

            return redirect('poll:notice-moderator-candidate-accepted')
        else:
            return redirect('poll:moderator-refuse', candidate_id=selected_candidate)


@login_required(login_url='poll:login')
@allowed_users(['Moderator'])
def moderator_refuse(request, candidate_id):
    context = standard_context(request)

    candidate = Candidate.objects.get(id=candidate_id)
    context['candidate'] = candidate

    form = ModerateCandidateForm()

    if request.method == 'POST':
        form = ModerateCandidateForm(request.POST, instance=candidate)

        if form.is_valid():
            form.save()

        moderated_user = get_object_or_404(User, username=candidate.author)
        switch_users_candidate_status(moderated_user, 'Application Draft')

        return redirect('poll:notice-moderator-candidate-refused')

    context['form'] = form

    return render(request, 'poll/moderator-refusal.html', context)


@login_required(login_url='poll:login')
@allowed_users(['Moderator'])
def moderator_instruction(request):
    context = standard_context(request)
    context['instruction'] = create_admin_data_or_use_current().instruction

    if request.method == 'POST':
        return redirect('poll:moderator-edit-instruction')

    return render(request, 'poll/moderator-instruction.html', context)


@login_required(login_url='poll:login')
@allowed_users()
def moderator_edit_instruction(request):
    context = standard_context(request)

    admin_data = create_admin_data_or_use_current()
    context['instruction'] = create_admin_data_or_use_current().instruction

    form = EditModeratorInstruction(instance=admin_data)

    if request.method == 'POST':
        form = EditModeratorInstruction(request.POST, instance=admin_data)

        if form.is_valid():
            form.save()

        return redirect('poll:notice-moderator-instruction-saved')

    context['form'] = form

    return render(request, 'poll/moderator-edit-instruction.html', context)


@login_required(login_url='poll:login')
@allowed_users(['Elector', 'Candidate'], ['all'])
def notice_access_is_forbidden(request):
    context = standard_context(request)
    return render(request, 'poll/notice-access-is-forbidden.html', context)


@login_required(login_url='poll:login')
@allowed_users(['Elector'])
def notice_participate_change_status(request):
    context = standard_context(request)
    return render(request, 'poll/notice-participate-change-status.html', context)


@login_required(login_url='poll:login')
@allowed_users(['Candidate'], ['Application Draft'])
def notice_participate_candidate_already_exists(request):
    context = standard_context(request)
    return render(request, 'poll/notice-participate-candidate-already-exists.html', context)


@login_required(login_url='poll:login')
@allowed_users(['Candidate'], ['Application Final'])
def notice_participate_sent(request):
    context = standard_context(request)
    return render(request, 'poll/notice-participate-sent.html', context)


@login_required(login_url='poll:login')
@allowed_users(['Candidate'], ['Application Draft'])
def notice_participate_update_sent(request):
    context = standard_context(request)
    return render(request, 'poll/notice-participate-update-sent.html', context)


@login_required(login_url='poll:login')
@allowed_users()
def notice_moderator_instruction_saved(request):
    context = standard_context(request)
    return render(request, 'poll/notice-moderator-instruction-saved.html', context)


@login_required(login_url='poll:login')
@allowed_users(['Moderator'])
def notice_moderator_candidate_accepted(request):
    context = standard_context(request)

poll/templates/poll/candidates.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'poll/include-head.html' %}

    <title>Candidates</title>
</head>
<body class="other-pages standard-font">
<div class="container standard-container">
    {% include 'poll/include-menu.html' %}

    <h1>List of Candidates</h1>
    <p>Click on candidate name to know more about.</p>

    {% for candidate in candidates_list %}
        {% if candidate.moderated == True %}
            <ul>
                <li>
                    <a href="{% url 'poll:detail' candidate.id %}">{{ candidate.name }} ({{ candidate.fraction }})</a>
                </li>
            </ul>
        {% endif %}
    {% endfor %}

    {% include 'poll/include-standard-navbar.html' %}
</div>
</body>
</html>

poll/templates/poll/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'poll/include-head.html' %}

    <title>Candidate's Data</title>
</head>
<body class="other-pages standard-font">
    <div class="container detail-container">
        {% include 'poll/include-menu.html' %}

        <p>{% include 'poll/include-detail.html' %}</p>

        {% include 'poll/include-standard-navbar.html' %}
    </div>
</body>
</html>

poll/templates/poll/hello.html
{% load static %}

<!DOCTYPE html>
<html lang="en-US">
<head>
    {% include 'poll/include-head.html' %}

    <title>Homepage</title>
</head>
<body class="other-pages standard-font">
    <div class="container standard-container">
        {% include 'poll/include-menu.html' %}
        <h1>Presidential Election</h1>
        <p>
            In this page you can see all candidates, participate and make a choice for the candidate.
            Remember: Each vote is important!
        </p>
        {% include 'poll/include-standard-navbar.html' %}
    </div>
</body>
</html>

poll/templates/poll/include-head.html
{% load static %}

<meta charset="UTF-8">
<meta name="author" content="AnoMorCH">
<link rel="stylesheet" type="text/css" href="{% static 'poll/style.css' %}">

poll/templates/poll/include-moderator-navbar.html
<table class="center">
    <tr>
        <td class="wide-td"><a href="{% url 'poll:moderator-hello' %}">Home</a></td>
        <td class="wide-td"><a href="{% url 'poll:moderator-instruction' %}">Instruction</a></td>
        <td class="wide-td"><a href="{% url 'poll:moderator-candidates' %}">Moderate</a></td>
    </tr>
</table>

poll/templates/poll/include-standard-navbar.html
<table class="center">
    <tr>
        <td class="wide-td"><a href="{% url 'poll:hello' %}">Home</a></td>
        <td class="wide-td"><a href="{% url 'poll:candidates' %}">Candidates</a></td>
    
        {% if not voted %}
            <td class="wide-td"><a href="{% url 'poll:choice' %}">Make a Choice</a></td>
        {% else %}
            <td class="wide-td"><a href="{% url 'poll:results' %}">Results</a></td>
        {% endif %}

        {% if candidate_status == 'Application Process' %}
            <td class="wide-td"><a href="{% url 'poll:create-participate-form' %}">Participate</a></td>
        {% elif candidate_status == 'Application Draft' %}
            <td class="wide-td"><a href="{% url 'poll:update-participate-form' username %}">Participate</a></td>
        {% elif candidate_status == 'Application Final' %}
            <td class="wide-td"><a href="{% url 'poll:participate-sent' %}">Participate</a></td>
        {% else %}
            <td class="wide-td"><a href="{% url 'poll:participate-warning-change-status' %}">Participate</a></td>
        {% endif %}
    </tr>
</table>

poll/templates/poll/moderator-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'poll/include-head.html' %}

    <title>Moderate a User</title>
</head>
<body class="other-pages standard-font">
    <div class="container detail-container">
        {% include 'poll/include-menu.html' %}

        {% include 'poll/include-detail.html' %}

        <form action="{% url 'poll:moderator-moderate' %}" method="post">
            {% csrf_token %}

            <div style="text-align: center;">
                <input type="submit" name="choice" value="ACCEPT" class="standard-button two-styled-button">
                <input type="submit" name="choice" value="REFUSE" class="standard-button two-styled-button">
            </div>

            <input type="hidden" id="candidate-id" name="candidate-id" value="{{ candidate.id }}">
        </form>

        <br>

        {% include 'poll/include-moderator-navbar.html' %}
    </div>
</body>
</html>

poll/templates/poll/notice-access-is-forbidden.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'poll/include-head.html' %}

    <title>Notice</title>
</head>
<body class="other-pages standard-font">
    <div class="container standard-container">
        {% include 'poll/include-menu.html' %}

        <h1>Access Is Forbidden</h1>
        <p>We are sorry. You can't visit this page. To gain access, please write your administrator.</p>

        {% include 'poll/include-standard-navbar.html' %}
    </div>
</body>
</html>

poll/templates/poll/notice-moderator-instruction-saved.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'poll/include-head.html' %}

    <title>Notice</title>
</head>
<body class="other-pages standard-font">
    <div class="container standard-container">
        {% include 'poll/include-menu.html' %}

        <h1>New Instruction's Been Saved</h1>
        <p>New instruction has been saved. You can continue your experience on the web page.</p>

        {% include 'poll/include-moderator-navbar.html' %}
    </div>
</body>
</html>

poll/templates/poll/notice-participate-change-status.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'poll/include-head.html' %}

    <title>Warning</title>
</head>
<body class="other-pages standard-font">
    <div class="container standard-container">
        {% include 'poll/include-menu.html' %}

        <h1>WARNING!</h1>
        <p>
            If you change your profile status, you will get access to create your participate form. In this case,
            your status will be changed on 'Candidate'!
        </p>

        <p style="text-align: center;">Want to continue?</p>

        <table class="center">
            <tr>
                <td class="wide-td"><a href="{% url 'poll:create-participate-form' %}">Yes</a></td>
                <td class="wide-td"><a href="{% url 'poll:hello' %}">No</a></td>
            </tr>
        </table>
    </div>
</body>
</html>

poll/templates/poll/notice-participate-sent.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'poll/include-head.html' %}

    <title>Notice</title>
</head>
<body class="other-pages standard-font">
    <div class="container standard-container">
        {% include 'poll/include-menu.html' %}

        <h1>Form's Been Sent</h1>
        <p>Form has been sent. Please, wait until it will be moderated. Result will be sent on your inner mail.</p>

        {% include 'poll/include-standard-navbar.html' %}
    </div>
</body>
</html>

poll/templates/poll/notifications.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'poll/include-head.html' %}

    <title>Notification</title>
</head>
<body class="other-pages standard-font">
    <div class="container standard-container">
        {% include 'poll/include-menu.html' %}

        <h1>Notifications</h1>
        <p>
            {% if moderated == True %}
                <p>Congratulations! Your participation form has been accepted.</p>
            {% else %}
                <p>Unfortunately, your participation form has been declined due the reason:</p>
                <p>{{ refusal_reason }}</p>
                <p>To send form again, please press the button 'Participate' below.</p>
            {% endif %}
        </p>

        {% include 'poll/include-standard-navbar.html' %}
    </div>
</body>
</html>

poll/templates/poll/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'poll/include-head.html' %}

    <title>Register</title>
</head>
<body class="other-pages standard-font">
    <div class="container standard-container">
        <h1>Register</h1>
        <form method="POST">
            {% csrf_token %}

            {{ form.username.label }}
            {{ form.username }}

            {{ form.email.label }}
            {{ form.email }}

            {{ form.password1.label }}
            {{ form.password1 }}

            {{ form.password2.label }}
            {{ form.password2 }}

            {{ form.errors }}

            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}

            <input type="submit" value="CREATE A NEW USER" class="standard-button one-styled-button">

            <div style="text-align: center">
                Already have an account? Please, <a href="{% url 'poll:login' %}">login</a>
            </div>
        </form>
    </div>
</body>
</html>

poll/templates/poll/results.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'poll/include-head.html' %}

    <title>Result</title>
</head>
<body class="other-pages standard-font">
    <div class="container standard-container">
        {% include 'poll/include-menu.html' %}

        <h1>Result</h1>
        {% for candidate in candidates_list %}
            {% if candidate.moderated == True %}
                <ul>
                    <li>{{ candidate.name }} ({{ candidate.fraction }}) - {{ candidate.votes }}</li>
                </ul>
            {% endif %}
        {% endfor %}

        {% include 'poll/include-standard-navbar.html' %}
    </div>
</body>
</html>